version: "2.3"

services:
    # ROS + ROS 2
    bridge:
        image: ros:foxy-ros1-bridge
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
        command: ros2 run ros1_bridge dynamic_bridge

    # ROS
    ros-master:
        image: ros:noetic-ros-core
        tty: true        # docker run -t
        command: stdbuf -o L roscore
        
    # ROS
    ros1:
        image: osrf/ros:noetic-desktop
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
        tty: true        # docker run -t
        command: rosrun rospy_tutorials talker
        
    # ROS 2
    ros2:
        image: osrf/ros:foxy-desktop
        command: ros2 run demo_nodes_cpp listener